baseURL = "https://engineering.dfautomation.com/"
languageCode = "en"
title = "DF Automation Engineering"
theme = "kiss"
copyright = "&copy; <a href=\"http://www.dfautomation.com\">DF Automation and Robotics Sdn Bhd</a> 2019"
enableEmoji = true
enableRobotsTXT = true
disqusShortname = "dfautomation-engineering"
googleAnalytics = "UA-119869560-1"

[params.info]
homeTitle = "DF Automation Engineering"
enableSocial = true

[params.social]
codepen = ""
email =  "careers@dfautomation.com"
facebook = "dfautomation"
github = "dfautomation"
instagram = ""
linkedin = ""
twitter = "dfautomation"

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true
